### ISSUE TITLE
Error installing on M-series Mac

### ISSUE THREAD

**Issue by colinvwood** [oxfordcontrol/clarabel-r#15]
Both `install.packages("clarabel")` and `remotes::install_github("oxfordcontrol/clarabel-r")` give the following error:

> The following warnings were emitted during compilation:
warning: savvy@0.6.4: x86_64-apple-darwin13.4: error: unsupported argument 'core2' to option '-march='
error: failed to run custom build command for `savvy v0.6.4`

For context, I'm an an arm64 Mac, using a conda environment where most packages are built for x86_64. Perhaps the compiler is confused by this because it looks like the above compiler option `core2` is only supposed to be used for x86 targets. Any insight is appreciated. 

The full output log is attached.

[log.txt](https://github.com/user-attachments/files/17576832/log.txt)

**Comment by bnaras** [comment]
I am pretty certain that this is due to the confusion that has arisen in the compiler toolchain given the conda environment modifications. (Indeed, this issue points to one of the strengths of R/CRAN infrastructure, where actual human beings ensure CRAN hosted packages on the major platforms, including ARM64 Mac. CRAN can be demanding, but there's a clear benefit, as I see it.)

I'd try installing a fresh R using homebrew, making sure it is found in your path, and then, in a shell that is not tainted by conda settings, install `clarabel`. You can install R as a cask, in which case you will use a binary `clarabel` package. You can also choose not to, in which case, it will compile and install it for you, provided you also install, if not already, all the tools needed for the compilation.

**Comment by colinvwood** [comment]
Hello @bnaras,

Thank you for your insight. Unfortunately, stepping outside of a conda environment isn't possible for me. I will just have to wait for the next release of bioconductor packages on bioconda I guess.
